export const DB_NAME = "snaptalk";
export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  MISSING_FIELDS: "MISSING_FIELDS",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  INVALID_INPUT: "INVALID_INPUT",
};